FROM golang:1.19-buster as builder

WORKDIR /app
COPY go.* ./
RUN go mod download

COPY . ./

RUN go build -v -o img-rekog.dev


FROM debian:buster-slim

RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080

COPY --from=builder /app/img-rekog.dev /app/img-rekog.dev    
CMD ["/app/img-rekog.dev"]